### ISSUE TITLE
Could you share the full genome fasta file before trimming

### ISSUE THREAD

**Issue by sajjadasaf** [hCoV-2019/lineages#1]
Please shared the full fasta file.

**Comment by rambaut** [comment]
The data can't be shared directly because of the GISAID agreement. You will need to download the data from gisaid.org.

**Comment by sajjadasaf** [comment]
there is no bulk download option it means we have to download one by one.

**Comment by rambaut** [comment]
You can ask for a bulk download option.

**Comment by sajjadasaf** [comment]
Thank you very much for your help.
