### ISSUE TITLE
Update LICENSE?

### ISSUE THREAD

**Issue by nileshpatra** [hCoV-2019/lineages#17]
Hi,

First off - thanks a lot for your work on lineages! :-)

We actually wanted to package this module as a debian package - for getting more packages to mitigate COVID-19
However, there is one problem -- currently the code is licensed under a Creative commons Source Attribution "Non commercial"
license which is not compatible with our free software guidelines.

It'd be great if you could instead change it to say, CC-by-SA simply. Also, this is the first time I've seen 'code' being licensed under Creative Commons license (I've mostly seen it for docs, art work et. al.) - how about using something like say MIT License?

Also, please consider vendoring the LICENSE file in the [release tarball](https://github.com/cov-lineages/lineages/releases/tag/2020-05-19-2)

**Comment by rambaut** [comment]
This repo was originally the data and documentation for the 'Dynamic Lineages' paper and thus the CC licence. The code in here are just utility scripts.
