### ISSUE TITLE
Again: Update LICENSE?

### ISSUE THREAD

**Issue by tillea** [hCoV-2019/lineages#18]
Hi,
since I can not re-open closed issues but we really need a solution for #17 I take the freedom to file a new issue:  I understand that you consider those utility scripts as not really important.  However, your code is used in at least one other project [pangolin](https://github.com/cov-lineages/pangolin).  We want to package it for Debian but we can't without a free license for lineages.  So it would be really helpful if you might consider a free license.
Thanks a lot, Andreas.

**Comment by rambaut** [comment]
We will look into it. We are trying to separate repositories which are primarily data/docs from the code repos. We will look at putting utility scripts in a separate repo.

**Comment by tillea** [comment]
Thanks a lot for the quick and helpful comment.  How can I learn about that new separate repository?  May be it is helpful to leave this issue open and close it once the repository is created by sending a link here.
