### ISSUE TITLE
are there plans to update the lineage assignments?

### ISSUE THREAD

**Issue by roblanf** [hCoV-2019/lineages#3]
I love the tool, and would like to ask just one question. 

Do you have plans to update the lineage assignments you show in https://github.com/hCoV-2019/lineages/tree/master/lineages/data

Regular updates would be very useful for those of us working to help local epidemiologists track outbreaks. It would save us having to recompute lineages from scratch as time goes by as well.

Rob

**Comment by seandavi** [comment]
A related, minor issue....

If you do updates, rather than using "versioned" filenames, it helps to settle on a single filename and then using git to manage versioning.

**Comment by rambaut** [comment]
Yes. We will be updating regularly and using github releases to version this. We do not have a v1.0 release yet as we are currently tweaking a few things.
