### ISSUE TITLE
pip version  2020-04-27   vs   1.7 

### ISSUE THREAD

**Issue by tseemann** [hCoV-2019/lineages#4]
```
lineages       2020-04-27 1.7    wheel
```
When i run `pip3 list --outdated` this appears.
What is the official numbering system?

**Comment by aineniamh** [comment]
I've been using date of data release as I thought it would be more informative to know when the data was recent since, because that's all that this repository really is (a pip-installable data store), rather than the standard naming sytem of 1.0.X.Y. This also made it more straightforward to add that into the output csv in `pangolin`.

**Comment by tseemann** [comment]
pip is telling me that 2020-04-27 is out of date and i need to upgrade to 1.7 
I still don't know what to do?

UPDATE: so i allowed pip to upgrade, now it doesn't find it:

```
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/pangolin", line 5, in <module>
    from pangolin.command import main
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/pangolin/command.py", line 11, in <module>
    import lineages
ModuleNotFoundError: No module named 'lineages'

```

So i went and manually installed git head:
```
pip3 upgrade git+https://github.com/hCoV-2019/lineages.git
      Successfully uninstalled lineages-1.7
Successfully installed lineages-2020-05-07
```

Has it just not been published to pypi maybe?

**Comment by aineniamh** [comment]
Yeah it's not on pypi. I've a section in the [readme](https://github.com/hCoV-2019/pangolin/blob/master/README.md#updating-pangolin) about updating.
To update to the latest release running `pip install --upgrade git+https://github.com/hCoV-2019/lineages.git` like you did should do the trick, or the conda environment would do it for you.

```
pip install --upgrade git+https://github.com/hCoV-2019/lineages.git
Collecting git+https://github.com/hCoV-2019/lineages.git
  Cloning https://github.com/hCoV-2019/lineages.git to /private/var/folders/6c/8t0c48s536q0x65wps6jp_d80000gr/T/pip-req-build-mqey56ah
  Running command git clone -q https://github.com/hCoV-2019/lineages.git /private/var/folders/6c/8t0c48s536q0x65wps6jp_d80000gr/T/pip-req-build-mqey56ah
Building wheels for collected packages: lineages
  Building wheel for lineages (setup.py) ... done
  Created wheel for lineages: filename=lineages-2020_05_07-cp36-none-any.whl size=1614216 sha256=ba7bbdd1cb0adb44c457ce49031ca3f3cf876cf2a1f29218bfd4b749edd9f82d
  Stored in directory: /private/var/folders/6c/8t0c48s536q0x65wps6jp_d80000gr/T/pip-ephem-wheel-cache-9uuqy2t3/wheels/da/1c/27/56777b47984321b8394c1e0c942bccab94cd90a657488e8b91
Successfully built lineages
Installing collected packages: lineages
Successfully installed lineages-2020-05-07

**Comment by tseemann** [comment]
Can you unpublish your 1.7 pip version?
Because pip will forever think 1.7 is newer than the date version ones.

**Comment by aineniamh** [comment]
https://pypi.org/project/lineages/
The 1.7 release isn't anything to do with this project, it's some other developer who has published to pypi under the name lineages. 
![Screenshot 2020-05-12 at 12 14 29](https://user-images.githubusercontent.com/11678307/81679481-2a83e880-944a-11ea-99df-ffaecf1d99d9.png)

Perhaps just specify the github when you're installing (`pip install --upgrade git+https://github.com/hCoV-2019/lineages.git`) and that'll direct you to the correct `lineages` package.

**Comment by tseemann** [comment]
Ideally, this repo should be renamed if it clashed with an existing python package.

**Comment by aineniamh** [comment]
It's not on pypi so shouldn't interact with the packages already there. Really, this was just a convenient way for us to host the data, in a way that I thought people who weren't familiar/ confident with the command line would be able to easily install as part of the conda environment, and would mean they wouldn't have to worry about relative paths or trying to pass multiple files through to pangolin.
