### ISSUE TITLE
Could you restore the GISAID ID column

### ISSUE THREAD

**Issue by roblanf** [hCoV-2019/lineages#5]
In the latest release you have removed the `GISAID ID` column from the `lineages.csv` file. 

This is an issue, because the `name` column does not match the GISAID names. E.g. you have removed spaces from names with spaces. 

It would really help to maintain a column of unique identifiers that can be matched to each GISAID record. I'm not wedded to GISAID ID, but it seems sensible. Other options would just be the full name of the sequence in GISAID with spaces, dates, and all. 

So, would it be possible to add back in a column of GISAID IDs, or something similar that serves as a unique and unchanged identifier from your `lineages.csv` to the data one can download from GISAID?

For back-compatibility I think it would be good to include the GISAID IDs, as in the previous version (this will be helpful to all those who are trying to build on your paper).

For forward ease-of-use, I think it would be great to have another column which is the full sequence name. That way you could expand in future to sequences that aren't GISAID without losing the generality.

Finally, as suggested in a previous issue which was since closed, it would be most useful if you could rename `lineages.2020-05-07.csv` to just `lineages.csv`: the versioning already takes care of the dates, and calling it `lineages.csv` means others can easily download the latest version of the lineages.

**Comment by joshsinger** [comment]
+1 for reinstating the GISAID IDs in the table.
+1 for renaming the file.
These things form part of the system's "contract" with other systems so it would help integration if they are as straightforward and stable as possible.

**Comment by tseemann** [comment]
There may be legal issues over the 'encoding' of gisaid data in this repo @roblanf

**Comment by roblanf** [comment]
Hmm. Legal issues with GISAID would be a pain. It's tricky to build on a repo that has *no* unique identifier that links names in the key output table to the data it represents though.

**Comment by AngieHinrichs** [comment]
Perhaps when possible, a representative sequence that is also in a public repository such as GenBank could be chosen, and a GenBank accession used?  It's easier to associate a GenBank accession with an EPI ID than an anonymised sequence.

**Comment by aineniamh** [comment]
To weigh in, the reason this field has been left out this week is that the metadata file I receive also dropped this column. I'm going to follow up and find out why this is, and if there's no actual reason we can't have it, I'll restore that column.

**Comment by roblanf** [comment]
Maybe it's not this simple in your case, but if you're working solely with GISAID sequences it should be possible to get the epi ID like this:

```
grep '>' gisaid.fasta | cut -d '|' -f2  > all_epiIDs.txt
``` 

If you could add a column for the full name as well, that would be very helpful.

**Comment by aineniamh** [comment]
With the new release, GISAID IDs have been restored (release took longer than expected)!
