### ISSUE TITLE
Un-annonymised Strain names in lineages.csv?

### ISSUE THREAD

**Issue by biocyberman** [hCoV-2019/lineages#7]
Hi @aineniamh Is it intentional to have original strain names in [this file](https://github.com/hCoV-2019/lineages/blob/master/lineages/data/lineages.2020-05-07.csv)?

**Comment by aineniamh** [comment]
Yes, this is intentional as this is how we know which records correspond to which lineages. It's not possible to link names with the sequence data from within the repo.

**Comment by biocyberman** [comment]
Thanks for the confirmation.
